config/routes.rb
Realty::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    get "online", :on => :collection
    resources :posters
  end

  resources :posters do
    resources :comments
  end

  root :to => 'posters#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :poster_id, :text, :user_id

  belongs_to :poster
  belongs_to :user
end

app/models/poster.rb
class Poster < ActiveRecord::Base
  attr_accessible :description, :name

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :nickname, :provider, :url, :username
  # attr_accessible :title, :body

  has_many :posters, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.find_for_facebook_oauth access_token
    if user = User.where(url: access_token.info.urls.Facebook).first
      user
    else
      if user = User.where(email: access_token.info.email).first
        user.update_attributes(provider: access_token.provider, url: access_token.info.urls.Facebook, username: access_token.extra.raw_info.name)
        user
      else
        User.create!(provider: access_token.provider, url: access_token.info.urls.Facebook, username: access_token.extra.raw_info.name, nickname: access_token.extra.raw_info.username, email: access_token.extra.raw_info.email, password: Devise.friendly_token[0,20])
      end
    end
  end

  def self.find_for_twitter_oauth auth
    user = User.where(provider: auth.provider, username: auth.uid).first
    if user
      return user
    else
      registered_user = User.where(email: auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else
        user = User.create(nickname: auth.info.name,
          provider: auth.provider,
          username: auth.info.name,
          email: auth.uid + "@twitter.com",
          password: Devise.friendly_token[0,20],
        )
      end
    end
  end


  def self.find_for_vk_oauth auth
    user = User.where(provider: auth[:info].provider, nickname: auth[:extra][:raw_info].screen_name).first
    if user
      return user
    else
      registered_user = User.where(url: auth[:info].urls[:Vkontakte]).first
      if registered_user
        return registered_user
      else
        user = User.create!(nickname: auth[:extra][:raw_info].screen_name,
          email: auth[:extra][:raw_info].screen_name + "@vk.com",
          provider: auth[:info].provider,
          username: "#{auth[:extra][:raw_info].first_name} #{auth[:extra][:raw_info].last_name}",
          url: auth[:info].urls[:Vkontakte],
          password: Devise.friendly_token[0,20],
        )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include Onliner

  before_filter { |c| c.track_user current_user unless current_user.nil?}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
    @poster = Poster.find(params[:poster_id])
    params[:comment][:user_id] = current_user.id
    @comment = @poster.comments.build(params[:comment])
    respond_to do |format|
      if @comment.save
        format.js
     end
  end
  end

  def show
  end

  def edit
  end

  def update
  end
end

app/controllers/posters_controller.rb
class PostersController < ApplicationController

  def index
    if current_user.nil?
      @posters = Poster.all
    else
      @posters = current_user.posters
    end

    respond_to do |format|
      format.html
      format.json { render json: @posters }
    end
  end

  def show
    @poster = Poster.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @poster }
    end
  end

  def new
   @poster = Poster.new(params[:poster])
   #@poster = current_user.posters.build
  end

  def edit
    @poster = Poster.find(params[:id])
  end

  def create
    @poster = current_user.posters.build(params[:poster])

    if verify_recaptcha
      @poster.save
      redirect_to [current_user, @poster]
    else
      flash[:recaptcha_error] = "There was an error with the recaptcha code below. Please re-enter the code and click submit."
      redirect_to new_user_poster_path
    end
  end

  def update
    @poster = Poster.find(params[:id])

    respond_to do |format|
      if @poster.update_attributes(params[:poster])
        format.html { redirect_to [current_user, @poster], notice: 'Poster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @poster.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @poster = Poster.find(params[:id])
    @poster.destroy

    respond_to do |format|
      format.html { redirect_to user_posters_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controler.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "Bad authentication with Facebook"
      redirect_to root_path
    end
  end

  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Twitter"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_uid"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def vkontakte
    @user = User.find_for_vk_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "Bad authentication with Vkontakte"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def online
  	@users = online_users    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posters_helper.rb
module PostersHelper
end

app/views/comments/_comments.html.haml
- @poster.comments.each do |comment|
  %p
    %strong #{comment.user.nickname}:
    = comment.text

app/views/comments/_form.html.haml
%p
  %strong #{@comment.user.nickname}:
  = @comment.text

app/views/comments/_new.html.haml
= form_for([@poster, @poster.comments.build], :remote => true, :html => { :id => 'new-comment-form' }) do |f|
  %p
    = f.label 'Add your comment'
    = f.text_area :text , class: "textarea-comment", rows: "2", cols: "40", placeholder: "Type your comment here"
  %p
    = f.submit

app/views/comments/create.js.erb
$('#comments').append('<%= escape_javascript(render 'form') %>');
$(".textarea-comment").val('');
$(".textarea-comment").focus();

app/views/comments/show.html.haml
%h1 Comments#show
%p Find me in app/views/comments/show.html.haml

app/views/comments/update.html.haml
%h1 Comments#update
%p Find me in app/views/comments/update.html.haml

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, msg|
  - if key == :notice
    .alert.alert-success= msg
  - elsif key == :error
    .alert.alert-error= msg
  - elsif key == :info
    .alert.alert-info= msg
  - else
    .alert.alert-block= msg

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      //%a.brand{:href => "#"} Some Store
      .nav-collapse
        %ul.nav
          %li= link_to "Home", root_path
          %li= link_to "Online users", online_users_path
        %ul.nav.pull-right
          - if user_signed_in?
            %li
              = link_to "#{current_user.username.blank? ? current_user.nickname : current_user.username}", edit_user_registration_path
            %li
              = link_to('Logout ', destroy_user_session_path, :method => :delete)
          - else
            %li
              = link_to('Login', new_user_session_path)
            %li
              = link_to image_tag("/assets/facebook.png"), user_omniauth_authorize_path(:facebook), alt: "Sign in with Facebook"
            %li
              = link_to image_tag("/assets/twitter.png"), user_omniauth_authorize_path(:twitter), alt: "Sign in with Twitter"
            %li
              = link_to image_tag("/assets/vkontakte.png"), user_omniauth_authorize_path(:vkontakte), alt: "Sign in with Vk"
            %li
              = link_to('Register', new_user_registration_path)

app/views/layouts/application.html.haml
%html
  %head
    %title Post
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      = render 'layouts/header'
      = render 'layouts/flash_messages'
      %section.round
        = yield

app/views/posters/_form.html.erb
<%= form_for [current_user, @poster], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="controls">
    <%= recaptcha_tags :display => {:theme => 'white'}%>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_posters_path, :class => 'btn' %>
  </div>
<% end %>

app/views/posters/edit.html.erb
<%- model_class = Poster -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posters/index.html.erb
<%- unless current_user.nil? -%>
<%- model_class = Poster -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posters.each do |poster| %>
      <tr>
        <td><%= poster.id %></td>
        <td><%= link_to poster.name, user_poster_path(current_user, poster) %></td>
        <td><%= poster.description %></td>
        <td><%=l poster.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_poster_path(current_user, poster), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_poster_path(current_user, poster),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_poster_path(current_user),
            :class => 'btn btn-primary' %>
<%- end -%>

app/views/posters/new.html.erb
<%- model_class = Poster -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posters/show.html.erb
<%- model_class = Poster -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @poster.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @poster.description %></dd>
</dl>

<div id='comments'>
  <h2>Comments</h2>
  <%= render 'comments/comments' %>
</div>

<%= render 'comments/new' %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              user_posters_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_poster_path(current_user.id, @poster), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_poster_path(current_user.id, @poster),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/users/online.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Id
      %th Email
      %th Username
  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.email
        %td= user.username
        